/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as DriverRouteRouteImport } from './routes/driver/route'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppCommunicationsRouteImport } from './routes/app/communications'
import { Route as AppComplianceRouteImport } from './routes/app/compliance'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppDispatchRouteImport } from './routes/app/dispatch'
import { Route as AppFuelRouteImport } from './routes/app/fuel'
import { Route as AppPodRouteImport } from './routes/app/pod'
import { Route as AppTrackingRouteImport } from './routes/app/tracking'
import { Route as AppWorkshopRouteImport } from './routes/app/workshop'
import { Route as AppBookingsIndexRouteImport } from './routes/app/bookings/index'
import { Route as AppBookingsBookingIdRouteImport } from './routes/app/bookings/$bookingId'
import { Route as AppBookingsNewRouteImport } from './routes/app/bookings/new'
import { Route as AppClientsIndexRouteImport } from './routes/app/clients/index'
import { Route as AppClientsClientIdRouteImport } from './routes/app/clients/$clientId'
import { Route as AppDriversIndexRouteImport } from './routes/app/drivers/index'
import { Route as AppDriversDriverIdRouteImport } from './routes/app/drivers/$driverId'
import { Route as AppFinanceReceivablesRouteImport } from './routes/app/finance/receivables'
import { Route as AppTripsIndexRouteImport } from './routes/app/trips/index'
import { Route as AppTripsTripIdRouteImport } from './routes/app/trips/$tripId'
import { Route as AppVehiclesIndexRouteImport } from './routes/app/vehicles/index'
import { Route as AppVehiclesVehicleIdRouteImport } from './routes/app/vehicles/$vehicleId'
import { Route as AppFinanceInvoicesIndexRouteImport } from './routes/app/finance/invoices/index'
import { Route as AppFinanceInvoicesInvoiceIdRouteImport } from './routes/app/finance/invoices/$invoiceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRouteRoute = DriverRouteRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommunicationsRoute = AppCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDispatchRoute = AppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFuelRoute = AppFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPodRoute = AppPodRouteImport.update({
  id: '/pod',
  path: '/pod',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkshopRoute = AppWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookingsIndexRoute = AppBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookingsBookingIdRoute = AppBookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookingsNewRoute = AppBookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDriversIndexRoute = AppDriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDriversDriverIdRoute = AppDriversDriverIdRouteImport.update({
  id: '/drivers/$driverId',
  path: '/drivers/$driverId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceReceivablesRoute = AppFinanceReceivablesRouteImport.update({
  id: '/finance/receivables',
  path: '/finance/receivables',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTripsIndexRoute = AppTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTripsTripIdRoute = AppTripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVehiclesIndexRoute = AppVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVehiclesVehicleIdRoute = AppVehiclesVehicleIdRouteImport.update({
  id: '/vehicles/$vehicleId',
  path: '/vehicles/$vehicleId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceInvoicesIndexRoute = AppFinanceInvoicesIndexRouteImport.update({
  id: '/finance/invoices/',
  path: '/finance/invoices/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceInvoicesInvoiceIdRoute =
  AppFinanceInvoicesInvoiceIdRouteImport.update({
    id: '/finance/invoices/$invoiceId',
    path: '/finance/invoices/$invoiceId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/driver': typeof DriverRouteRoute
  '/portal': typeof PortalRouteRoute
  '/app/audit': typeof AppAuditRoute
  '/app/communications': typeof AppCommunicationsRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/fuel': typeof AppFuelRoute
  '/app/pod': typeof AppPodRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/app/bookings/$bookingId': typeof AppBookingsBookingIdRoute
  '/app/bookings/new': typeof AppBookingsNewRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/drivers/$driverId': typeof AppDriversDriverIdRoute
  '/app/finance/receivables': typeof AppFinanceReceivablesRoute
  '/app/trips/$tripId': typeof AppTripsTripIdRoute
  '/app/vehicles/$vehicleId': typeof AppVehiclesVehicleIdRoute
  '/app/bookings/': typeof AppBookingsIndexRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/drivers/': typeof AppDriversIndexRoute
  '/app/trips/': typeof AppTripsIndexRoute
  '/app/vehicles/': typeof AppVehiclesIndexRoute
  '/app/finance/invoices/$invoiceId': typeof AppFinanceInvoicesInvoiceIdRoute
  '/app/finance/invoices/': typeof AppFinanceInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/driver': typeof DriverRouteRoute
  '/portal': typeof PortalRouteRoute
  '/app/audit': typeof AppAuditRoute
  '/app/communications': typeof AppCommunicationsRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/fuel': typeof AppFuelRoute
  '/app/pod': typeof AppPodRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/app/bookings/$bookingId': typeof AppBookingsBookingIdRoute
  '/app/bookings/new': typeof AppBookingsNewRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/drivers/$driverId': typeof AppDriversDriverIdRoute
  '/app/finance/receivables': typeof AppFinanceReceivablesRoute
  '/app/trips/$tripId': typeof AppTripsTripIdRoute
  '/app/vehicles/$vehicleId': typeof AppVehiclesVehicleIdRoute
  '/app/bookings': typeof AppBookingsIndexRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/drivers': typeof AppDriversIndexRoute
  '/app/trips': typeof AppTripsIndexRoute
  '/app/vehicles': typeof AppVehiclesIndexRoute
  '/app/finance/invoices/$invoiceId': typeof AppFinanceInvoicesInvoiceIdRoute
  '/app/finance/invoices': typeof AppFinanceInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/driver': typeof DriverRouteRoute
  '/portal': typeof PortalRouteRoute
  '/app/audit': typeof AppAuditRoute
  '/app/communications': typeof AppCommunicationsRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dispatch': typeof AppDispatchRoute
  '/app/fuel': typeof AppFuelRoute
  '/app/pod': typeof AppPodRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/app/bookings/$bookingId': typeof AppBookingsBookingIdRoute
  '/app/bookings/new': typeof AppBookingsNewRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/drivers/$driverId': typeof AppDriversDriverIdRoute
  '/app/finance/receivables': typeof AppFinanceReceivablesRoute
  '/app/trips/$tripId': typeof AppTripsTripIdRoute
  '/app/vehicles/$vehicleId': typeof AppVehiclesVehicleIdRoute
  '/app/bookings/': typeof AppBookingsIndexRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/drivers/': typeof AppDriversIndexRoute
  '/app/trips/': typeof AppTripsIndexRoute
  '/app/vehicles/': typeof AppVehiclesIndexRoute
  '/app/finance/invoices/$invoiceId': typeof AppFinanceInvoicesInvoiceIdRoute
  '/app/finance/invoices/': typeof AppFinanceInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/driver'
    | '/portal'
    | '/app/audit'
    | '/app/communications'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/dispatch'
    | '/app/fuel'
    | '/app/pod'
    | '/app/tracking'
    | '/app/workshop'
    | '/app/bookings/$bookingId'
    | '/app/bookings/new'
    | '/app/clients/$clientId'
    | '/app/drivers/$driverId'
    | '/app/finance/receivables'
    | '/app/trips/$tripId'
    | '/app/vehicles/$vehicleId'
    | '/app/bookings/'
    | '/app/clients/'
    | '/app/drivers/'
    | '/app/trips/'
    | '/app/vehicles/'
    | '/app/finance/invoices/$invoiceId'
    | '/app/finance/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/driver'
    | '/portal'
    | '/app/audit'
    | '/app/communications'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/dispatch'
    | '/app/fuel'
    | '/app/pod'
    | '/app/tracking'
    | '/app/workshop'
    | '/app/bookings/$bookingId'
    | '/app/bookings/new'
    | '/app/clients/$clientId'
    | '/app/drivers/$driverId'
    | '/app/finance/receivables'
    | '/app/trips/$tripId'
    | '/app/vehicles/$vehicleId'
    | '/app/bookings'
    | '/app/clients'
    | '/app/drivers'
    | '/app/trips'
    | '/app/vehicles'
    | '/app/finance/invoices/$invoiceId'
    | '/app/finance/invoices'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/driver'
    | '/portal'
    | '/app/audit'
    | '/app/communications'
    | '/app/compliance'
    | '/app/dashboard'
    | '/app/dispatch'
    | '/app/fuel'
    | '/app/pod'
    | '/app/tracking'
    | '/app/workshop'
    | '/app/bookings/$bookingId'
    | '/app/bookings/new'
    | '/app/clients/$clientId'
    | '/app/drivers/$driverId'
    | '/app/finance/receivables'
    | '/app/trips/$tripId'
    | '/app/vehicles/$vehicleId'
    | '/app/bookings/'
    | '/app/clients/'
    | '/app/drivers/'
    | '/app/trips/'
    | '/app/vehicles/'
    | '/app/finance/invoices/$invoiceId'
    | '/app/finance/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DriverRouteRoute: typeof DriverRouteRoute
  PortalRouteRoute: typeof PortalRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/communications': {
      id: '/app/communications'
      path: '/communications'
      fullPath: '/app/communications'
      preLoaderRoute: typeof AppCommunicationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dispatch': {
      id: '/app/dispatch'
      path: '/dispatch'
      fullPath: '/app/dispatch'
      preLoaderRoute: typeof AppDispatchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/fuel': {
      id: '/app/fuel'
      path: '/fuel'
      fullPath: '/app/fuel'
      preLoaderRoute: typeof AppFuelRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/pod': {
      id: '/app/pod'
      path: '/pod'
      fullPath: '/app/pod'
      preLoaderRoute: typeof AppPodRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tracking': {
      id: '/app/tracking'
      path: '/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workshop': {
      id: '/app/workshop'
      path: '/workshop'
      fullPath: '/app/workshop'
      preLoaderRoute: typeof AppWorkshopRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/bookings/': {
      id: '/app/bookings/'
      path: '/bookings'
      fullPath: '/app/bookings/'
      preLoaderRoute: typeof AppBookingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/bookings/$bookingId': {
      id: '/app/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/app/bookings/$bookingId'
      preLoaderRoute: typeof AppBookingsBookingIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/bookings/new': {
      id: '/app/bookings/new'
      path: '/bookings/new'
      fullPath: '/app/bookings/new'
      preLoaderRoute: typeof AppBookingsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/clients'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients/$clientId': {
      id: '/app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/app/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/drivers/': {
      id: '/app/drivers/'
      path: '/drivers'
      fullPath: '/app/drivers/'
      preLoaderRoute: typeof AppDriversIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/drivers/$driverId': {
      id: '/app/drivers/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/app/drivers/$driverId'
      preLoaderRoute: typeof AppDriversDriverIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/finance/receivables': {
      id: '/app/finance/receivables'
      path: '/finance/receivables'
      fullPath: '/app/finance/receivables'
      preLoaderRoute: typeof AppFinanceReceivablesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/trips/': {
      id: '/app/trips/'
      path: '/trips'
      fullPath: '/app/trips/'
      preLoaderRoute: typeof AppTripsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/trips/$tripId': {
      id: '/app/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/app/trips/$tripId'
      preLoaderRoute: typeof AppTripsTripIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vehicles/': {
      id: '/app/vehicles/'
      path: '/vehicles'
      fullPath: '/app/vehicles/'
      preLoaderRoute: typeof AppVehiclesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vehicles/$vehicleId': {
      id: '/app/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/app/vehicles/$vehicleId'
      preLoaderRoute: typeof AppVehiclesVehicleIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/finance/invoices/': {
      id: '/app/finance/invoices/'
      path: '/finance/invoices'
      fullPath: '/app/finance/invoices/'
      preLoaderRoute: typeof AppFinanceInvoicesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/finance/invoices/$invoiceId': {
      id: '/app/finance/invoices/$invoiceId'
      path: '/finance/invoices/$invoiceId'
      fullPath: '/app/finance/invoices/$invoiceId'
      preLoaderRoute: typeof AppFinanceInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppCommunicationsRoute: typeof AppCommunicationsRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDispatchRoute: typeof AppDispatchRoute
  AppFuelRoute: typeof AppFuelRoute
  AppPodRoute: typeof AppPodRoute
  AppTrackingRoute: typeof AppTrackingRoute
  AppWorkshopRoute: typeof AppWorkshopRoute
  AppBookingsBookingIdRoute: typeof AppBookingsBookingIdRoute
  AppBookingsNewRoute: typeof AppBookingsNewRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppDriversDriverIdRoute: typeof AppDriversDriverIdRoute
  AppFinanceReceivablesRoute: typeof AppFinanceReceivablesRoute
  AppTripsTripIdRoute: typeof AppTripsTripIdRoute
  AppVehiclesVehicleIdRoute: typeof AppVehiclesVehicleIdRoute
  AppBookingsIndexRoute: typeof AppBookingsIndexRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppDriversIndexRoute: typeof AppDriversIndexRoute
  AppTripsIndexRoute: typeof AppTripsIndexRoute
  AppVehiclesIndexRoute: typeof AppVehiclesIndexRoute
  AppFinanceInvoicesInvoiceIdRoute: typeof AppFinanceInvoicesInvoiceIdRoute
  AppFinanceInvoicesIndexRoute: typeof AppFinanceInvoicesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppCommunicationsRoute: AppCommunicationsRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDispatchRoute: AppDispatchRoute,
  AppFuelRoute: AppFuelRoute,
  AppPodRoute: AppPodRoute,
  AppTrackingRoute: AppTrackingRoute,
  AppWorkshopRoute: AppWorkshopRoute,
  AppBookingsBookingIdRoute: AppBookingsBookingIdRoute,
  AppBookingsNewRoute: AppBookingsNewRoute,
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppDriversDriverIdRoute: AppDriversDriverIdRoute,
  AppFinanceReceivablesRoute: AppFinanceReceivablesRoute,
  AppTripsTripIdRoute: AppTripsTripIdRoute,
  AppVehiclesVehicleIdRoute: AppVehiclesVehicleIdRoute,
  AppBookingsIndexRoute: AppBookingsIndexRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppDriversIndexRoute: AppDriversIndexRoute,
  AppTripsIndexRoute: AppTripsIndexRoute,
  AppVehiclesIndexRoute: AppVehiclesIndexRoute,
  AppFinanceInvoicesInvoiceIdRoute: AppFinanceInvoicesInvoiceIdRoute,
  AppFinanceInvoicesIndexRoute: AppFinanceInvoicesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DriverRouteRoute: DriverRouteRoute,
  PortalRouteRoute: PortalRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
